name: CosmicJackpot
version: ${project.version}
main: me.alexdev.cosmicjackpot.CosmicJackpot
author: Alex
api-version: 1.16
depend: [Vault]
commands:
  jackpot:
    description: Jackpot command.
    usage: /jackpot
